# Applications
install node
install zsh
install phantomjs
install chromedriver
install sitespeed.io
install android-sdk

# Homebrew Cask
tap caskroom/cask
install brew-cask

# Homebrew Fonts
tap caskroom/fonts
install font-inconsolata-dz

 
